agents:
  queue: default
steps:
  - label: "build vllm"
    commands: |
      podman build \
        --build-arg max_jobs=8 \
        --build-arg VLLM_CPU_DISABLE_AVX512=false \
        --build-arg GIT_REPO_CHECK=1 \
        -f Dockerfile.cpu
