agents:
  queue: default
steps:
  - label: "hello world"
    commands: |
      python --version
      python -m venv .venv
      source .venv/bin/activate


      echo $HOME
      env

      pip install uv
      uv pip install vllm==0.6.3.post1

      vllm --help
