agents:
  queue: default
steps:
  - label: "env info"
    commands: |
      echo "- python: $(python --version)"
      echo "- working directory is: $(pwd)"
      echo "- env: "
      env

  - label: "install vllm"
    commands: |
      python -m venv .venv
      source .venv/bin/activate

      pip install uv
      uv pip install vllm==0.6.3.post1

      vllm --help
